server:
  port: 8080

spring:
  application:
    name: Authentication-XETAX

  datasource:
    url: jdbc:mysql://localhost:3306/authentication
    username: root
    password: Vcp@18209
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true

    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true

  security:
    oauth2:
      client:
        registration:

          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - email
              - profile
              - openid

          github:
            client-id: ${GITHUB_CLIENT_ID:test-client-id}
            client-secret: ${GITHUB_CLIENT_SECRET:test-client-secret}
            scope:
              - read:user
              - user:email

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false

logging:
  level:
    org.hibernate.SQL: DEBUG

security:
  jwt:
    secret: ${JWT_SECRET:my-super-secret-key-1234567890123456789012345678901234567890}
    issuer: ${ISSUER:api.substring.com}
    access-ttl-seconds: ${JWT_ACCESS_TTL_SECONDS:3600}
    refresh-ttl-seconds: ${JWT_REFRESH_TTL_SECONDS:86400}
    refresh-token-cookie-name: ${JWT_REFRESH_COOKIE_NAME:refreshToken}
    cookie-secure: ${JWT_COOKIE_SECURE:true}
    cookie-http-only: ${JWT_COOKIE_HTTP_ONLY:true}
    cookie-same-site: ${JWT_COOKIE_SAME_SITE:lax}
    cookie-domain: ${JWT_DOMAIN:localhost}